# we are extending everything from tomcat:7.0 image ...
FROM tomcat:7.0
MAINTAINER margaret_redman_jeffrey_longo
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY SWE645_HW1.war /usr/local/tomcat/webapps/